FROM public.ecr.aws/lambda/python:3.12

COPY src/lambda/requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY src/lambda/*.py ${LAMBDA_TASK_ROOT}/

CMD ["handler.lambda_handler"]
